<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Info_ip_client_model extends CI_Model
{

    public $table = 'info_ip_client';
    public $id = 'id_infoip';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('client', 'info_ip_client.id_client = client.id_client');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->join('client', 'info_ip_client.id_client = client.id_client');
        $this->db->like('id_infoip', $q);
        // $this->db->or_like('id_client', $q);
        $this->db->or_like('user_pppoe', $q);
        $this->db->or_like('pass_ppoe', $q);
        $this->db->or_like('ip_radio', $q);
        $this->db->or_like('nama_radio', $q);
        $this->db->or_like('ip_router', $q);
        $this->db->or_like('user_paas_router', $q);
        $this->db->or_like('merk_router', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->join('client', 'info_ip_client.id_client = client.id_client');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_infoip', $q);
        // $this->db->or_like('id_client', $q);
        $this->db->or_like('user_pppoe', $q);
        $this->db->or_like('pass_ppoe', $q);
        $this->db->or_like('ip_radio', $q);
        $this->db->or_like('nama_radio', $q);
        $this->db->or_like('ip_router', $q);
        $this->db->or_like('user_paas_router', $q);
        $this->db->or_like('merk_router', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Info_ip_client_model.php */
/* Location: ./application/models/Info_ip_client_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-17 06:19:01 */
/* http://harviacode.com */