<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Paket_model extends CI_Model
{

    public $table = 'paket';
    public $id = 'id_paket';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->join('jenis_paket', 'paket.id_jp = jenis_paket.id_jp');
        $this->db->like('id_paket', $q);
        // $this->db->or_like('id_jp', $q);
        $this->db->or_like('bandwith', $q);
        $this->db->or_like('harga', $q);
        $this->db->or_like('kap_peng', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        //$paket_data= $this->db->query("SELECT * FROM paket inner join jenis_paket on paket.id_jp=jenis_paket.id_jp");
        $this->db->join('jenis_paket', 'paket.id_jp = jenis_paket.id_jp');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_paket', $q);
        $this->db->or_like('bandwith', $q);
        $this->db->or_like('harga', $q);
        $this->db->or_like('kap_peng', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Paket_model.php */
/* Location: ./application/models/Paket_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-31 17:20:30 */
/* http://harviacode.com */