<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pemasukan_model extends CI_Model
{

    public $table = 'pembayaran';
    public $id = 'id_pem';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pem', $q);
        $this->db->or_like('tgl_pem', $q);
        $this->db->or_like('id_client', $q);
        $this->db->or_like('total_bayar', $q);
        $this->db->or_like('bukti_pem', $q);
        $this->db->or_like('id_paket', $q);
        $this->db->or_like('bulan', $q);
        $this->db->or_like('status', $q);
        $this->db->or_like('status_notif', $q);
        $this->db->from($this->table);
            return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pem', $q);
        $this->db->or_like('tgl_pem', $q);
        $this->db->or_like('id_client', $q);
        $this->db->or_like('total_bayar', $q);
        $this->db->or_like('bukti_pem', $q);
        $this->db->or_like('id_paket', $q);
        $this->db->or_like('bulan', $q);
        $this->db->or_like('status', $q);
        $this->db->or_like('status_notif', $q);
        $this->db->limit($limit, $start);
            return $this->db->get($this->table)->result();
    }
    function get_data_stok(){
        // $query = $this->db->query("SELECT * , Month(tgl_peng) as bulan FROM pengeluaran  group by Month(tgl_peng), Year(tgl_peng)");
        $query = $this->db->query("SELECT Sum(total_bayar) as total , Year(tgl_pem) as tahun FROM pembayaran Where status=2 group by Year(tgl_pem)");
        if($query->num_rows() > 0){
            foreach($query->result() as $data){
                $hasil[] = $data;
            }
            return $hasil;
        }
    }

}

/* End of file Pengeluaran_model.php */
/* Location: ./application/models/Pengeluaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-29 15:40:11 */
/* http://harviacode.com */