<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tagihan_model extends CI_Model
{

    public $table = 'pembayaran';
    public $id = 'id_pem';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get_where($this->table, 'status', 0)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get_where($this->table, 'status', 0)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pem', $q);
        $this->db->or_like('tgl_pem', $q);
        $this->db->or_like('id_client', $q);
        $this->db->or_like('total_bayar', $q);
        $this->db->or_like('bukti_pem', $q);
        $this->db->or_like('id_paket', $q);
        $this->db->or_like('bulan', $q);
        $this->db->or_like('jatuh_temp', $q);
        $this->db->or_like('status', $q);
        $this->db->or_like('status_notif', $q);
        $this->db->from($this->table);
        $this->db->where('status', 0);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pem', $q);
        $this->db->or_like('tgl_pem', $q);
        $this->db->or_like('id_client', $q);
        $this->db->or_like('total_bayar', $q);
        $this->db->or_like('bukti_pem', $q);
        $this->db->or_like('id_paket', $q);
        $this->db->or_like('bulan', $q);
        $this->db->or_like('jatuh_temp', $q);
        $this->db->or_like('status', $q);
        $this->db->or_like('status_notif', $q);
        $this->db->limit($limit, $start);
        return $this->db->get_where($this->table, 'status', 0)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

}

/* End of file Pembayaran_model.php */
/* Location: ./application/models/Pembayaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-05 14:31:03 */
/* http://harviacode.com */