<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Laporan_pertahun extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->library('form_validation');
    }

    public function index()
    {
        if(isset($_SESSION['username'])){
        $data = array(
            'start' => 0,
            "header" => "admin/header","nav" => "admin/nav",
            "container" => "admin/laporan_pertahun/laporan_pertahun_list",
            'user'=>$this->db->GET_WHERE('admin',['username' => $this->session->userdata('username')])->row_array(),
        );
        $this->load->view("template", $data);
        } else {
            redirect(site_url("login_admin"));
        }
    }

    public function word()
    {
        header("Content-type: application/vnd.ms-word");
        header("Content-Disposition: attachment;Filename=rekap_semua_laporan_pertahun.doc");

        $data = array(
            // 'laporan_pertahun_data' => $this->Laporan_pertahun_model->get_all(),
            'start' => 0
        );
        
        $this->load->view('admin/laporan_pertahun/laporan_pertahun_doc',$data);
    }

    public function word_tahun($id)
    {
        header("Content-type: application/vnd.ms-word");
        header("Content-Disposition: attachment;Filename=rekap_laporan_pertahun_'$id'.doc");

        $data = array(
            // 'laporan_pertahun_data' => $this->Laporan_pertahun_model->get_all(),
            'id' =>$id,
            'start' => 0
        );
        
        $this->load->view('admin/laporan_pertahun/laporan_pertahun_doc_tahun',$data);
    }


}

/* End of file laporan_pertahun.php */
/* Location: ./application/controllers/laporan_pertahun.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-29 15:40:11 */
/* http://harviacode.com */