<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pemasukan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pemasukan_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        if(isset($_SESSION['username'])){
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'pemasukan/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'pemasukan/index.html?q=' . urlencode($q);
        } else {
            $config['query_string_segment'] = 'start';
            $config['full_tag_open'] = '<div class="card-footer text-right"><nav class="d-inline-block"> <ul class="pagination mb-0"><div class="row">';
            // $config['next_tag_open'] = '<li class="page-item active"><a class="page-link" href="#">';
            $config['next_link'] = '<div class="col-3"><i class="fas fa-chevron-right"></i></div>';
            // $config['next_tag_close'] = '</a></li>';
            $config['prev_link'] = '<div class="col-3"><i class="fas fa-chevron-left"></i></div>';
            // $config['prev_tag_open'] = '<li class="page-item"><a class="page-link" href="#">';
            // $config['prev_tag_close'] = '</a></li>';
            $config['cur_tag_open'] = '<li class="page-item active "><a class="page-link" href="#">';
            $config['cur_tag_close'] = '</a></li>';
            // $config['num_tag_open'] = '<li class="page-item "><a class="page-link" href="#"></a>';
            // $config['num_tag_close'] = '</li>';
            $config['base_url'] = base_url() . 'pemasukan/index.html';
            $config['first_url'] = base_url() . 'pemasukan/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Pemasukan_model->total_rows($q);
        $pemasukan = $this->Pemasukan_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'pembayaran_data' => $pemasukan,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            "header" => "admin/header","nav" => "admin/nav",
            "container" => "admin/pemasukan/pemasukan_list",
            'user'=>$this->db->GET_WHERE('admin',['username' => $this->session->userdata('username')])->row_array(),
            'grafik'=>$this->Pemasukan_model->get_data_stok(),
        );
        $this->load->view("template", $data);
        } else {
            redirect(site_url("login_admin"));
        }
    }

    public function word()
    {
        header("Content-type: application/vnd.ms-word");
        header("Content-Disposition: attachment;Filename=rekap_semua_pemasukan.doc");

        $data = array(
            // 'pemasukan_data' => $this->Pemasukan_model->get_all(),
            'start' => 0
        );
        
        $this->load->view('admin/pemasukan/pemasukan_doc',$data);
    }

    public function word_tahun($id)
    {
        header("Content-type: application/vnd.ms-word");
        header("Content-Disposition: attachment;Filename=rekap_pemasukan_'$id'.doc");

        $data = array(
            // 'pemasukan_data' => $this->Pemasukan_model->get_all(),
            'id' =>$id,
            'start' => 0
        );
        
        $this->load->view('admin/pemasukan/pemasukan_doc_tahun',$data);
    }


}

/* End of file pemasukan.php */
/* Location: ./application/controllers/pemasukan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-29 15:40:11 */
/* http://harviacode.com */